# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/mo/code/reactor

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/mo/code/reactor

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mo/code/reactor/CMakeFiles /home/mo/code/reactor//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mo/code/reactor/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named reactor

# Build rule for target.
reactor: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 reactor
.PHONY : reactor

# fast build rule for target.
reactor/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reactor.dir/build.make CMakeFiles/reactor.dir/build
.PHONY : reactor/fast

#=============================================================================
# Target rules for targets named reactor_autogen_timestamp_deps

# Build rule for target.
reactor_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 reactor_autogen_timestamp_deps
.PHONY : reactor_autogen_timestamp_deps

# fast build rule for target.
reactor_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reactor_autogen_timestamp_deps.dir/build.make CMakeFiles/reactor_autogen_timestamp_deps.dir/build
.PHONY : reactor_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named reactor_autogen

# Build rule for target.
reactor_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 reactor_autogen
.PHONY : reactor_autogen

# fast build rule for target.
reactor_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reactor_autogen.dir/build.make CMakeFiles/reactor_autogen.dir/build
.PHONY : reactor_autogen/fast

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reactor.dir/build.make CMakeFiles/reactor.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reactor.dir/build.make CMakeFiles/reactor.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reactor.dir/build.make CMakeFiles/reactor.dir/main.cpp.s
.PHONY : main.cpp.s

plots.o: plots.cpp.o
.PHONY : plots.o

# target to build an object file
plots.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reactor.dir/build.make CMakeFiles/reactor.dir/plots.cpp.o
.PHONY : plots.cpp.o

plots.i: plots.cpp.i
.PHONY : plots.i

# target to preprocess a source file
plots.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reactor.dir/build.make CMakeFiles/reactor.dir/plots.cpp.i
.PHONY : plots.cpp.i

plots.s: plots.cpp.s
.PHONY : plots.s

# target to generate assembly for a file
plots.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reactor.dir/build.make CMakeFiles/reactor.dir/plots.cpp.s
.PHONY : plots.cpp.s

reactor.o: reactor.cpp.o
.PHONY : reactor.o

# target to build an object file
reactor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reactor.dir/build.make CMakeFiles/reactor.dir/reactor.cpp.o
.PHONY : reactor.cpp.o

reactor.i: reactor.cpp.i
.PHONY : reactor.i

# target to preprocess a source file
reactor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reactor.dir/build.make CMakeFiles/reactor.dir/reactor.cpp.i
.PHONY : reactor.cpp.i

reactor.s: reactor.cpp.s
.PHONY : reactor.s

# target to generate assembly for a file
reactor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reactor.dir/build.make CMakeFiles/reactor.dir/reactor.cpp.s
.PHONY : reactor.cpp.s

reactor_autogen/mocs_compilation.o: reactor_autogen/mocs_compilation.cpp.o
.PHONY : reactor_autogen/mocs_compilation.o

# target to build an object file
reactor_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reactor.dir/build.make CMakeFiles/reactor.dir/reactor_autogen/mocs_compilation.cpp.o
.PHONY : reactor_autogen/mocs_compilation.cpp.o

reactor_autogen/mocs_compilation.i: reactor_autogen/mocs_compilation.cpp.i
.PHONY : reactor_autogen/mocs_compilation.i

# target to preprocess a source file
reactor_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reactor.dir/build.make CMakeFiles/reactor.dir/reactor_autogen/mocs_compilation.cpp.i
.PHONY : reactor_autogen/mocs_compilation.cpp.i

reactor_autogen/mocs_compilation.s: reactor_autogen/mocs_compilation.cpp.s
.PHONY : reactor_autogen/mocs_compilation.s

# target to generate assembly for a file
reactor_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reactor.dir/build.make CMakeFiles/reactor.dir/reactor_autogen/mocs_compilation.cpp.s
.PHONY : reactor_autogen/mocs_compilation.cpp.s

third_party/qcustomplot/qcustomplot.o: third_party/qcustomplot/qcustomplot.cpp.o
.PHONY : third_party/qcustomplot/qcustomplot.o

# target to build an object file
third_party/qcustomplot/qcustomplot.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reactor.dir/build.make CMakeFiles/reactor.dir/third_party/qcustomplot/qcustomplot.cpp.o
.PHONY : third_party/qcustomplot/qcustomplot.cpp.o

third_party/qcustomplot/qcustomplot.i: third_party/qcustomplot/qcustomplot.cpp.i
.PHONY : third_party/qcustomplot/qcustomplot.i

# target to preprocess a source file
third_party/qcustomplot/qcustomplot.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reactor.dir/build.make CMakeFiles/reactor.dir/third_party/qcustomplot/qcustomplot.cpp.i
.PHONY : third_party/qcustomplot/qcustomplot.cpp.i

third_party/qcustomplot/qcustomplot.s: third_party/qcustomplot/qcustomplot.cpp.s
.PHONY : third_party/qcustomplot/qcustomplot.s

# target to generate assembly for a file
third_party/qcustomplot/qcustomplot.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reactor.dir/build.make CMakeFiles/reactor.dir/third_party/qcustomplot/qcustomplot.cpp.s
.PHONY : third_party/qcustomplot/qcustomplot.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... reactor_autogen"
	@echo "... reactor_autogen_timestamp_deps"
	@echo "... reactor"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... plots.o"
	@echo "... plots.i"
	@echo "... plots.s"
	@echo "... reactor.o"
	@echo "... reactor.i"
	@echo "... reactor.s"
	@echo "... reactor_autogen/mocs_compilation.o"
	@echo "... reactor_autogen/mocs_compilation.i"
	@echo "... reactor_autogen/mocs_compilation.s"
	@echo "... third_party/qcustomplot/qcustomplot.o"
	@echo "... third_party/qcustomplot/qcustomplot.i"
	@echo "... third_party/qcustomplot/qcustomplot.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

